version: '3.8'

services:
  # Python Telegram Bot
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.telegram
    container_name: invoice-telegram-bot
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./database/invoices.db:/app/database/invoices.db
      - ./dashboard_output:/app/dashboard_output
    restart: unless-stopped

networks:
  invoice-network:
    driver: bridge